/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RideType = IDL.Variant({ 'car' : IDL.Null, 'bike' : IDL.Null });
export const TaxiBooking = IDL.Record({
  'bookingId' : IDL.Nat,
  'dropoffLocation' : IDL.Text,
  'user' : IDL.Principal,
  'riderEmail' : IDL.Text,
  'riderName' : IDL.Text,
  'rideType' : RideType,
  'pickupDateTime' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTaxiBooking' : IDL.Func([IDL.Nat], [], []),
  'createTaxiBooking' : IDL.Func(
      [RideType, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllTaxiBookings' : IDL.Func([], [IDL.Vec(TaxiBooking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTaxiBooking' : IDL.Func([IDL.Nat], [IDL.Opt(TaxiBooking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTaxiBookings' : IDL.Func([], [IDL.Vec(TaxiBooking)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTransportSlotAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RideType = IDL.Variant({ 'car' : IDL.Null, 'bike' : IDL.Null });
  const TaxiBooking = IDL.Record({
    'bookingId' : IDL.Nat,
    'dropoffLocation' : IDL.Text,
    'user' : IDL.Principal,
    'riderEmail' : IDL.Text,
    'riderName' : IDL.Text,
    'rideType' : RideType,
    'pickupDateTime' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTaxiBooking' : IDL.Func([IDL.Nat], [], []),
    'createTaxiBooking' : IDL.Func(
        [RideType, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllTaxiBookings' : IDL.Func([], [IDL.Vec(TaxiBooking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTaxiBooking' : IDL.Func([IDL.Nat], [IDL.Opt(TaxiBooking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTaxiBookings' : IDL.Func([], [IDL.Vec(TaxiBooking)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTransportSlotAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };