/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type RideType = { 'car' : null } |
  { 'bike' : null };
export interface TaxiBooking {
  'bookingId' : bigint,
  'dropoffLocation' : string,
  'user' : Principal,
  'riderEmail' : string,
  'riderName' : string,
  'rideType' : RideType,
  'pickupDateTime' : string,
  'pickupLocation' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTaxiBooking' : ActorMethod<[bigint], undefined>,
  'createTaxiBooking' : ActorMethod<
    [RideType, string, string, string, string, string],
    bigint
  >,
  'getAllTaxiBookings' : ActorMethod<[], Array<TaxiBooking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTaxiBooking' : ActorMethod<[bigint], [] | [TaxiBooking]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTaxiBookings' : ActorMethod<[], Array<TaxiBooking>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTransportSlotAvailable' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];